### ISSUE TITLE
Can't create cast

### ISSUE THREAD

**Issue by waptik** [dylsteck/litecast-web#3]
Getting the following error message when looking at network traffic but the frontend displays a toast with a successful message.

<img width="961" alt="image" src="https://github.com/dylsteck/litecast-web/assets/1687551/3d42a831-bb7a-4547-b350-07252f77c14f">

**Comment by dylsteck** [comment]
Going to look into this and report back, thanks for flagging @waptik!

**Comment by dylsteck** [comment]
The new commit I just pushed(below) should fix this problem -- thanks again for flagging!

https://github.com/dylsteck/litecast-web/commit/7db4cf66242092a1128b5456b061cd91254278e5

**Comment by waptik** [comment]
Great! I can confirm that casting is working now!
You should probably check the mobile app too cos last time i tried casting through it, it wasn't also working.

UPDATE: Closing modal on desktop doesn't work, had to refresh the tab.
